# Generated by Django 3.2.9 on 2021-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0005_auto_20211118_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
