# Generated by Django 3.2.9 on 2021-11-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0007_auto_20211118_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poligonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_std', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lidar.document')),
            ],
        ),
    ]
