# Generated by Django 3.2.9 on 2021-11-18 21:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0010_auto_20211118_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poligonos',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='poligonos',
            name='h_max',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='poligonos',
            name='h_mean',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='poligonos',
            name='h_min',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='poligonos',
            name='h_range',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='poligonos',
            name='h_std',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
