# Generated by Django 3.2.9 on 2021-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0011_auto_20211118_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_id',
            field=models.CharField(default='id_', max_length=50),
        ),
    ]
